FROM bde2020/spark-master:3.3.0-hadoop3.3

RUN apk update && apk add --no-cache \
    gcc \
    gfortran \
    libgfortran \
    openblas-dev \
    build-base \
    python3-dev \
    musl-dev

RUN pip3 install --upgrade pip

WORKDIR /app

COPY /flaskapp . 

RUN pip3 install -r requirements.txt

EXPOSE 5550
